### ISSUE TITLE
coredump when trying to open Settings

### ISSUE THREAD

**Issue by oberon-manjaro** [martyr-deepin/deepin-terminal-gtk#10]
On Manjaro - and apparently on plain Archlinux, too - clicking on 'Settings' results in core dump.
gdb bt below.

**Comment by oberon-manjaro** [comment]
This is still with **deepin-terminal-2.4.1**, will try again with **v2.4.2** a little later. Just, when I look at the commits since 2.4.1 release it looks to me that nothing relevant has been changed since.

**Comment by oberon-manjaro** [comment]
```
(gdb) run
Starting program: /usr/bin/deepin-terminal 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe95d5700 (LWP 2451)]
[New Thread 0x7fffe8dd4700 (LWP 2452)]
[New Thread 0x7fffe3fff700 (LWP 2453)]
[New Thread 0x7fffe0e10700 (LWP 2454)]
[Thread 0x7fffe3fff700 (LWP 2453) exited]

Thread 1 "deepin-terminal" received signal SIGSEGV, Segmentation fault.
0x00007ffff49b4a14 in free () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff49b4a14 in free () at /usr/lib/libc.so.6
#1  0x0000000000445bee in widgets_preference_construct ()
#2  0x000000000042422f in  ()
#3  0x00007ffff7802f75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#4  0x00007ffff7814f82 in  () at /usr/lib/libgobject-2.0.so.0
#5  0x00007ffff781dbdc in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#6  0x00007ffff781dfbf in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#7  0x00007ffff7802f75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#8  0x00007ffff7814f82 in  () at /usr/lib/libgobject-2.0.so.0
#9  0x00007ffff781dbdc in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#10 0x00007ffff781e46b in g_signal_emit_by_name () at /usr/lib/libgobject-2.0.so.0
#11 0x000000000041dd0e in  ()
#12 0x00007ffff3c981c8 in ffi_call_unix64 () at /usr/lib/libffi.so.6
#13 0x00007ffff3c97c2a in ffi_call () at /usr/lib/libffi.so.6
#14 0x00007ffff78037ae in g_cclosure_marshal_generic () at /usr/lib/libgobject-2.0.so.0
#15 0x00007ffff7802f75 in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#16 0x00007ffff781537d in  () at /usr/lib/libgobject-2.0.so.0
#17 0x00007ffff781dbdc in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#18 0x00007ffff781dfbf in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#19 0x00007ffff7b0d53c in  () at /usr/lib/libgio-2.0.so.0
#20 0x00007ffff7afce74 in  () at /usr/lib/libgio-2.0.so.0
#21 0x00007ffff55bc66a in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#22 0x00007ffff55bca20 in  () at /usr/lib/libglib-2.0.so.0
#23 0x00007ffff55bcd42 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#24 0x00007ffff710eed5 in gtk_main () at /usr/lib/libgtk-3.so.0
#25 0x0000000000476a24 in application_main ()
#26 0x00000000004174e0 in main ()
(gdb)
```

**Comment by oberon-manjaro** [comment]
I just built **v2.4.2** and can confirm that the issue has not changed with latest version.

**Comment by oberon-manjaro** [comment]
Might be related to https://github.com/linuxdeepin/deepin-terminal/issues/8

**Comment by felixonmars** [comment]
#8 is not relevant AFAICS. It should be a problem with vala 0.36.

Bisected to these commits:
https://github.com/GNOME/vala/commit/e2422670e9438153faa697c5aedc7653289f7354
https://github.com/GNOME/vala/commit/971f474f105bd1bbee7144eb4183635084c96821

Someone more familiar with vala could have a look.

**Comment by manateelazycat** [comment]
@felixonmars has test yesterday:
vala 0.36.3 failed
vala 0.34.6 ok
vala 0.36.0 failed

It's seen a bug of vala that cause by commits:
https://github.com/GNOME/vala/commit/e2422670e9438153faa697c5aedc7653289f7354
https://github.com/GNOME/vala/commit/971f474f105bd1bbee7144eb4183635084c96821

I will figure out how to make deepin-terminal works with newer vala.
